### ISSUE TITLE
Getting Error 24 on Install

### ISSUE THREAD

**Issue by kscz** [hharte/mm_manager#11]
Hey there! I have a NT5U phone which is failing to get it's initial upload and disconnecting partway through.

I've been futzing around to get everything working and I can't quite seem to make it past this.

With a full upload I disconnect partway through table 151 -
```
T-->M RX: flags=20 [ DIS | REQ |  ---  | Seq:0], len=  5 (datalen=  0), crc=0378.
receive_mm_packet: Received disconnect status OK from terminal.
receive_mm_packet: Hanging up modem.

T-->M RX: flags=20 [ DIS | REQ |  ---  | Seq:0], len=  5 (datalen=  0), crc=0378.
send_mm_packet: Received NACK, retrying 0.
        Table 151 (0x97) DLOG_MT_INTL_SBR_TABLE progress: ( 81%) -  490 /  604
        Table 151 (0x97) DLOG_MT_INTL_SBR_TABLE progress: (100%) -  604 /  604
mm_download_tables: Download failed, hanging up modem.
```

And with a "small" download I disconnect on table 136 -
```
T-->M RX: flags=08 [ --- | ACK |  ---  | Seq:0], len=  5 (datalen=  0), crc=0366.
        Table 136 (0x88) DLOG_MT_NPA_NXX_TABLE_1 progress: (100%) -  203 /  203
Waiting for ACK for table 136 (0x88)                                                                                   

T-->M RX: flags=20 [ DIS | REQ |  ---  | Seq:0], len=  5 (datalen=  0), crc=0378.            
receive_mm_packet: Received disconnect status OK from terminal.                              
receive_mm_packet: Hanging up modem.                                                                                   
wait_for_table_ack: ERROR: Did not receive ACK for table ID 136 (0x88), status=02
```

Here's the initial connection blob (I changed the phone number because while it is fake, it is a possible-to-dial phone number):
```
        Terminal ID 8005551234: Processing Table ID 10 (0x0a) DLOG_MT_TERM_STATUS                                                                                                                                                   [112/1813]
                Terminal serial number 1111111111, Terminal Status Word: 0x0000000080
                        Terminal Status: Reserved TELEPHONY_STATUS_BIT_7
                                                                                                                       
        Terminal ID 8005551234: Processing Table ID 60 (0x3c) DLOG_MT_SW_VERSION
                                     Terminal Type: 02 (0x02)
                               Control ROM Edition: 06CAA17                      
                                   Control Version: V1.0
                             Telephony ROM Edition: QQ1RWU                                   
                                 Telephony Version: V2.2                                                               
                        Validator Hardware Version: 20                                                                 
                        Validator Software Version: 10
        Seq 2: Send DLOG_MT_CASH_BOX_STATUS table as requested by terminal.      
        Load Cashbox status: 2022-04-29 21:34:25 Total: $0.00 (  0% full): CA N:0 D:0 Q:0 $:0 - US N:0 D:0 Q:0 $:0
        Sending Table ID 38 (0x26) DLOG_MT_CASH_BOX_STATUS... 
```

Let me know if there's anything I could do to debug this! I have some patches I'll submit soon which make it so that the code works with my USRobotics model 5637 modem

**Comment by kscz** [comment]
[install_fail_logs.zip](https://github.com/hharte/mm_manager/files/8596392/install_fail_logs.zip)
I've included two separate failures as a zip - the one where I used the `-s` CLI option, and the one where I just ran without the "small"

**Comment by hharte** [comment]
Hello @kscz ,

The reason why the download fails is that your Millennium terminal is running firmware version 06CAA17, which is MTR 1.7.  mm_manager supports MTR 1.20 and 2.x.  One option is to burn a new EPROM with https://github.com/muccc/millennium/blob/master/firmware/NPA1S01/dump2/NT_FW_1.20_STM27C2001_32DIP to update your terminal to MTR 1.20.  Another option is to wait for me to add support for MTR 1.7 to mm_manager.  MTR 1.7 firmware is quite old, and missing some features of the newer firmware.

If you need help with burning a new EPROM, please contact me via email.

Take care,
Howard

**Comment by kscz** [comment]
Ha! Well that does explain things - do you have any guidance on diving in to navigate the code differences? I'll go ahead and close this issue - but perhaps I should open one for v1.7 support? Thanks for the quick reply!

**Comment by hharte** [comment]
Sure, you can add a feature request for MTR 1.7 support.

**Comment by hharte** [comment]
MTR 1.7 and 1.9 should be supported as of this commit: dd0a9116f1a6ab3c1d03260a8022e91a6e63a2fe
