### ISSUE TITLE
mm_manager won't serve tables to phone after power loss

### ISSUE THREAD

**Issue by Ilikemining1** [hharte/mm_manager#14]
Hi,

I've discovered an issue with mm_manager when it comes to power loss / table RAM corruption.  When a forced download occurs after a terminal has gone out of service due to power loss or RAM corruption, mm_manager still thinks that the tables haven't been changed since they were last uploaded and doesn't send them. This causes terminal error 34 when doing a forced download. I think this could be remedied by checking for a power loss alarm status and allowing for a full download of tables.

When experimenting earlier, deleting table_update.log seemed to fix this issue, but it does cause the terminal to not be able to pull tables by itself and it goes out of service.

Thanks

**Comment by hharte** [comment]
Good find!  Overloading the “force Download” to only download the modified tables is in and of itself, a bug.  I just did this to make it easier to iterate through table changes for debugging.

what you propose is a good compromise, I’ll look into it.

Thanks for filing this feedback.
