### ISSUE TITLE
Modem initialization issue

### ISSUE THREAD

**Issue by Fda777** [hharte/mm_manager#15]
I have a Millennium payphone I am working on and I have setup mm_manager on a raspberry pi 4 with US Robotics 5637 usb modem. Each time I try to start mm_manager the modem fails to initialize after the program resets to modem with the ATZ string. The problem appears to be centered around the initialization string. Below is a detail of the error along with details of my setup. 
 
pi@raspberrypi:~/Payphone/mm_manager/build $ ./mm_manager -m -n 4235550001 -f  /dev/ttyACM0 -vv -l install.dlog -p install.pcap
mm_manager v0.8 [dev-dirty] - (c) 2020-2022, Howard M. Harte

Default Table directory: tables/default
Terminal-specific Table directory: tables/<terminal_id>
Using access code: 2727378
Using key card number: 4012888888
Manager Inter-packet Tx gap: 100ms.
Using Primary NCC number: 4235550001
Using Secondary NCC number: 4235550001
Baud Rate: 19200
Resetting modem: 'ATZ'
Initializing modem:  'ATE=1 S0=1 S7=3 &D2 +MS=B212'
Error initializing modem.
pi@raspberrypi:~/Payphone/mm_manager/build & 
 
My current setup is as follows: 
Millennium Payphone with NNK1F05 1.13 firmware English/French
Teltone TLS - 5 Telephone line simulator
US Robotics 5637 usb modem
Raspberry pi 4 running Linux version 5.10.103-v71+
 
I have also installed this on a windows 10 pc and had the same result. I have been troubleshooting this issue for a while and have noticed that if I insert the modem string "-i ATZ" the modem will initialize and switch to waiting on terminal without the error. Once the terminal calls the modem will not answer. Any help would be greatly appreciated.

**Comment by supersat** [comment]
That particular modem needs `+MS=Bell212A` instead of `+MS=B212`. Try `-i "ATE=1 S0=1 S7=3 &D2 +MS=Bell212A"`.

**Comment by Fda777** [comment]
Supersat, Thank you for the help. That got the modem to initialize. I tried to provision the phone and called and the modem picked up however there was no reaction mm_manager. After about 10 seconds or so the modem disconnected. I am going to change the baud rate around and see if I can get it to do anything.

**Comment by supersat** [comment]
Just a random guess:

Are you going through the Millennium install process? At one point, it should perform an answer detection test. If it doesn't immediately hang up after the modem answers, then something's broken with the answer detection -- you either need an Inferred Answer Supervision module or polarity reversal on answer to make it work.

**Comment by Fda777** [comment]
Actually yes, I am going through the install process. The answer detection test is where I am at currently. My phone does not have the Inferred answer supervision module installed. When I run the answer detection sequence I can hear 3 separate modem tones in the receiver then the modem disconnects, followed by the terminal giving me a #51 error in the display.  According to the Nortel manual #51 is a answer supervision failure.

**Comment by hharte** [comment]
@Fda777 if your terminal does not have the IAS module installed, then as @supersat says, the phone line that your terminal is connected to needs to provide answer supervision by reversing the polarity on the line when the far end answers.  Most PBXs and FXS ports can be configured to provide answer supervision.

The Millennium terminal does not actually communicate via modem until the part of the setup where the terminal display shows “Download in progress”

**Comment by Fda777** [comment]
I want to thank both of you for your help. I will go investigate the answer supervision side of the equation and see what adjustments I need to make to my line simulator. Anyway, I am going to close this issue out since my original question pertained to the modem string in mm_manger and that is working now. Once again, I appreciate the help.
