### ISSUE TITLE
Latest update breaks modem

### ISSUE THREAD

**Issue by troykrahn** [hharte/mm_manager#2]
With the latest update I can no longer get my modem to initialize, any attempt to run mm_manager fails with `Error Initializing Modem`

# Modem
My modem is a Multitech Systems MultiModem2 (model MT5600). I've looked inside this modem and it does appear to have a Conexant chipset. 

# Operating System
I am running a Debian based Linux system.

# Steps to Reproduce

1. Power on modem
2. Run `./mm_manager -m -n 18005551234 -f /dev/ttyX -l install.txt`
3. `mm_manager` seems to reset the modem, but fails afterwards

![Annotation 2020-01-25 153229](https://user-images.githubusercontent.com/32440755/73126352-f9a9a180-3f87-11ea-9171-8105da819c86.jpg)
 
# Troubleshooting Performed
I have tried restarting the modem and resetting it manually, but neither seem to make any difference.

**Comment by hharte** [comment]
Check the last commit to mm_modem.c, I changed the baud rate from 19200 to 1200.  Can you please try changing it back?  I will add a command line parameter for it.

**Comment by troykrahn** [comment]
I've changed the speed back to 19200 but the issue prevails. I'm wondering if there's something different about my modem that just makes it difficult to interface with.

**Comment by hharte** [comment]
I ordered the MT5600, will give it a try when I receive it.

**Comment by hharte** [comment]
This issue is resolved by 519b0729700e2393592a7e449c1abff32b058291.
