### ISSUE TITLE
MM not communicating with serial port

### ISSUE THREAD

**Issue by commoncathode** [hharte/mm_manager#22]
As the title describes, I cannot get past modem initialization, and I believe it's because there is no serial port communication at all. My user is in the dialout group, I have run `chown user /dev/ttyUSB0` to be safe, tried different serial ports, different baud rates, tried different modems, nothing. I have used a supraFAXmodem v.32 biz and a USR 5686 and both are working when accessed directly using qodem (my terminal program of choice). 
As an example, here's a typical exchange when trying to start mm:
```
$ sudo ./mm_manager -b 9600 -m -n 6666666666 -f /dev/ttyUSB0 -vv -l install.dlog -p install.pcap -i 'ATE=1 S0=4 S7=3 &D2'
mm_manager v0.8 [Unknown] - (c) 2020-2023, Howard M. Harte

Default Table directory: tables/default
Terminal-specific Table directory: tables/<terminal_id>
Using access code: 2727378
Using key card number: 4012888888
Manager Inter-packet Tx gap: 100ms.
Using Primary NCC number: 6666666666
Using Secondary NCC number: 6666666666
Baud Rate: 9600
Resetting modem: 'ATZ'
Error initializing modem.
free(): double free detected in tcache 2
Aborted
$

```
I have also tried omitting the init string and sending it before trying the mm command, but I think the issue is that the software is not talking to the serial port for some reason. There must be something big and obvious that I'm missing. Any help appreciated. Thanks!

**Comment by hharte** [comment]
Hello,

Thank you for your bug report.  There are several versions of the USR 5686, I've tried two of them and put details of the configuration on the Wiki: [USR5686](https://github.com/hharte/mm_manager/wiki/supported-modems#us-robotics-5686e-and-5686g)

Can you please provide more details about your operating system, modem, USB to Serial adapter?  With that information,  I can try to reproduce the issue.

Thanks,
Howard

**Comment by commoncathode** [comment]
Hello,

Modem is a 5686, no E or G. I tried sending ATI to get the full model number but can’t seem to get echo working; the tx light activates on the modem but not the serial adapter. Works fine on the Supra modem so it may be an issue with the USR.

OS is Ubuntu 22.04 LTS, serial adapter is a genuine FTDI FT232R.

-Patrick

**Comment by hharte** [comment]
Hello Patrick,

Did you check the DIP switch settings on your modem?  Also, are you using a 9-pin to 25-pin “modem” cable between the USB serial adapter and the modem?

The lack of echo could be a setting on the modem or a flow control issue due to the serial adapter settings or cabling.  Can you communicate with the USR modem using minicom?  Ie, ATZ<return> and the modem should respond with “OK”

Take care,
Howard

**Comment by commoncathode** [comment]
Hi Howard,

Yes, it's a 9 to 25 pin cable - the one I was using is straight thru, so I used a null modem cable after that to get the TX/RX lines in the correct places. I swapped it out using one I made myself and verified the DIP switches were set correctly - still no echo.
I'm wondering if there's an issue with the modem itself since the Supra modem echoes fine with both sets of cables.

**Comment by commoncathode** [comment]
Forgot to mention: the no echo issue was caused by an incorrect power supply for the modem. I erroneously assumed DC would work, but only the newer USR modems are DC. The old ones require AC to make the negative voltages required for rs232.
