### ISSUE TITLE
My modem can't handshake a rev01 control board but works just fine on the smd rev.

### ISSUE THREAD

**Issue by photon303** [hharte/mm_manager#3]
Got 2 Millennium Payphones
seem that they have 2 different modem chipset 

My modem is a Supra fax modem 288 external (old school, serial port with a rockwell chipset)
my current init string: ATB1

Able to provision the phone with the modem chip 73K324l-28IH just fine
Won't handshake at all with my other payphone with the 73K212ASL-IP
It is supposed to be a known working board.

Do you know how I can troubleshoot the communication issue for the modem, any way I can get a verbose of the handshake?

Telephony setup is a Cisco IAD2431-16FXS. My testing has been done on the FXS side of the switch. Did a board swap on the payphones to be sure the issue was not related to the FXS port or backboard in the payphone.

**Comment by photon303** [comment]
Seem like it was the modem.... did trow money at the problem and got the Lenovo 56k usb modem suggested in the documentation and everything just works...

I'm closing the ticket unless anybody willing to add support for that old beast.
Nice work btw... really love that project! Tkx!

**Comment by hharte** [comment]
I’m glad it’s working fine with the Lenovo modem, and thanks for the update.  It’s good to know that there is a difference in modem behavior between the two PCP revisions, I was not aware of that before.  I’ll keep that in mind for future testing.
