### ISSUE TITLE
Provisioning Failure

### ISSUE THREAD

**Issue by Ritchie828** [hharte/mm_manager#5]
This would appear to be the same issue (or similar to) the one experienced by troykrahn and also a common point of failure as  I know of at least one other user with the same issue. 
I consistently receive disconnect flags at the same point (table 151) when provisioning.
![modem discon](https://user-images.githubusercontent.com/68869656/88598922-0d65bb80-d030-11ea-8e47-53156e48b156.png)

mm_manager does appear to be communicating with the phone initially as basic information is passed between them. (Time, date, system info etc.)
![mill info](https://user-images.githubusercontent.com/68869656/88599065-72211600-d030-11ea-917c-19624490e2e9.png)
 and the mm_manager log. 
[install.log](https://github.com/hharte/mm_manager/files/4984936/install.log)

I would appreciate any insight or help on this problem.

Jay

**Comment by hharte** [comment]
Hello Jay,

I suggest updating your Millennium terminal's control ROM firmware to v1.20.  The tables are different between different ROM versions, and I only figured out the tables for v1.20 and v2.20 (the latest ROM versions for the through-hole and surface mount control PCP's respectively.)

Please contact me via email if you need help.

Thanks,
Howard
