### ISSUE TITLE
Tables definition in mm_util.c

### ISSUE THREAD

**Issue by photon303** [hharte/mm_manager#9]
Table definition in mm_util.c : 
"DLOG_MT_NPA_NXX_TABLE_15", // 0xa0
"DLOG_MT_NPA_NXX_TABLE_16", // 0xa1

It does not have the same table number in the millennium payphone wiki -> https://wiki.muc.ccc.de/millennium:start
DLOG_MT_NPA_NXX_TABLE_15 is listed as 0x73 for mtr 1.x and 2.x(single compressed) or table 0x9a for mtr 2.x(double compressed LCD table)
DLOG_MT_NPA_NXX_TABLE_16 is listed as 0x9b  for mtr 2.x only (double compressed LCD table)

Who have the right info?

**Comment by supersat** [comment]
Based on the info I have, it might actually depend on the firmware version. If it's an international build, then the numbers change.

But I have DLOG_MT_NPA_NXX_TABLE_1 = 74 for the international build and DLOG_MT_NPA_NXX_TABLE_1 = 101 for the regular build. DLOG_MT_NPA_NXX_TABLE_15 is 0x73 in the regular build, but doesn't exist in the international build.

**Comment by photon303** [comment]
so, it would need more than 2 sets, at least 4 I imagine... or variables in the tables set defined upon detection of the version of the phone. Interesting... I would be curious to see the table list for the international version, is it a recent revision?

**Comment by supersat** [comment]
The information I have is pretty old and supposedly corresponds to version PBAXS03

**Comment by hharte** [comment]
It appears that different Millennium Terminal Releases (MTRs) changed the LCD table structure over time, from the original Uncompressed LCD tables in MTR <= 1.7, to Compressed LCD tables in 1.9, and double-compressed LCD tables in MTR 1.20 and 2.x.  This commit: b4039992a09b3538f90c31991013770d8cf680c4 adds support for the three LCD table variants to mm_manager.
